export const sample_official: any[] = [
  {
    id: "1",
    convocation: "1",
    processing: "Procesamiento rellenar",
    name: "Jhon",
    lastname: "Hurtado Garcia",
    position: "empresario",
  },
  {
    id: "2",
    convocation: "1",
    processing: "Procesamiento rellenar",
    name: "Mario",
    lastname: "Pon Garcia",
    position: "sastre",
  },
  {
    id: "3",
    convocation: "1",
    processing: "Procesamiento rellenar",
    name: "Nicolas",
    lastname: "Hurtado Garcia",
    position: "empresario",
  },
  {
    id: "4",
    convocation: "1",
    processing: "Procesamiento rellenar",
    name: "Agusto",
    lastname: "Pon Garcia",
    position: "sastre",
  },
];

export const sample_student: any[] = [
  {
    authorization: "1",
    ci_passport: "18786dsadasd",
    name: "Jhon",
    lastname: "Hurtado Garcia",
    awarded_specialty: "buzo",
    gender: "masculino",
    address: "calle libertad #203",
    foreign: true,
    country: "Bolivia",
    pre_university: "Saul",
    entrance_exams: ["Matematica"],
    academic_index: 4,
    grade_average: 5.6,
    scholarship_right: true,
    ces: "PUE",
  },
  {
    authorization: "1",
    ci_passport: "empresario",
    name: "Mario",
    lastname: "Pon Garcia",
    awarded_specialty: "buzo",
    gender: "masculino",
    address: "calle libertad #203",
    foreign: false,
    country: "Cuba",
    pre_university: "Saul",
    entrance_exams: ["Matematica"],
    academic_index: 4,
    grade_average: 5.6,
    scholarship_right: false,
    ces: "PUE",
  },
  {
    authorization: "1",
    ci_passport: "empresario",
    name: "Ana",
    lastname: "Hurtado Garcia",
    awarded_specialty: "buzo",
    gender: "femenino",
    address: "calle libertad #203",
    foreign: true,
    country: "Bolivia",
    pre_university: "Saul",
    entrance_exams: ["Matematica"],
    academic_index: 4,
    grade_average: 5.6,
    scholarship_right: true,
    ces: "PUE",
  },
  {
    authorization: "1",
    ci_passport: "empre242667898sario",
    name: "Max",
    lastname: "Pon Garcia",
    awarded_specialty: "buzo",
    gender: "masculino",
    address: "calle libertad #203",
    foreign: false,
    country: "Cuba",
    pre_university: "Saul",
    entrance_exams: ["Matematica"],
    academic_index: 4,
    grade_average: 5.6,
    scholarship_right: false,
    ces: "PUE",
  },
];

export const sample_diul_student: any[] = [
  {
    student: {
      authorization: "1",
      ci_passport: "empresario",
      name: "Ana",
      lastname: "Hurtado Garcia",
      awarded_specialty: "buzo",
      gender: "femenino",
      address: "calle libertad #203",
      foreign: true,
      country: "Bolivia",
      pre_university: "Saul",
      entrance_exams: ["Matematica"],
      academic_index: 4,
      grade_average: 5.6,
      scholarship_right: true,
      ces: "PUE",
    },
    type: ["Cambio", "Fijo"],
    studentOf: "Pepe",
    description: "Cambio",
    allOfficials: false,
  },
  {
    student: {
      authorization: "1",
      ci_passport: "18786dsadasd",
      name: "Jhon",
      lastname: "Hurtado Garcia",
      awarded_specialty: "buzo",
      gender: "masculino",
      address: "calle libertad #203",
      foreign: true,
      country: "Bolivia",
      pre_university: "Saul",
      entrance_exams: ["Matematica"],
      academic_index: 4,
      grade_average: 5.6,
      scholarship_right: true,
      ces: "PUE",
    },
    type: ["Cambio", "Fijo"],
    studentOf: "Pepe",
    description: "Cambio",
    allOfficials: false,
    awarded_career: "Informatica",
    education_center: "Uci",
    scholarship_right: false,
  },
  {
    student: {
      authorization: "1",
      ci_passport: "empre242667898sario",
      name: "Max",
      lastname: "Pon Garcia",
      awarded_specialty: "buzo",
      gender: "masculino",
      address: "calle libertad #203",
      foreign: false,
      country: "Cuba",
      pre_university: "Saul",
      entrance_exams: ["Matematica"],
      academic_index: 4,
      grade_average: 5.6,
      scholarship_right: false,
      ces: "PUE",
    },
    type: ["Cambio", "Fijo"],
    studentOf: "Pepe",
    description: "Cambio",
    allOfficials: false,
    awarded_career: "Informatica",
    education_center: "Uci",
    scholarship_right: false,
  },
];

export const sample_cip_student: any[] = [
  {
    student: {
      authorization: "1",
      ci_passport: "empre242667898sario",
      name: "Max",
      lastname: "Pon Garcia",
      awarded_specialty: "buzo",
      gender: "masculino",
      address: "calle libertad #203",
      foreign: false,
      country: "Cuba",
      pre_university: "Saul",
      entrance_exams: ["Matematica"],
      academic_index: 4,
      grade_average: 5.6,
      scholarship_right: false,
      ces: "PUE",
    },
    type: ["Cambio", "Fijo"],
    description: "Cambio",
    allOfficials: false,
    awarded_career: "Informatica",
    education_center: "Uci",
    scholarship_right: false,
    // entrance_exams!: string[];
  },
  {
    student: {
      authorization: "1",
      ci_passport: "18786dsadasd",
      name: "Jhon",
      lastname: "Hurtado Garcia",
      awarded_specialty: "buzo",
      gender: "masculino",
      address: "calle libertad #203",
      foreign: true,
      country: "Bolivia",
      pre_university: "Saul",
      entrance_exams: ["Matematica"],
      academic_index: 4,
      grade_average: 5.6,
      scholarship_right: true,
      ces: "PUE",
    },
    type: ["Cambio", "Fijo"],
    description: "Cambio",
    allOfficials: false,
    awarded_career: "Informatica",
    education_center: "Uci",
    scholarship_right: false,
    // entrance_exams!: string[];
  },
  {
    student: {
      authorization: "1",
      ci_passport: "empresario",
      name: "Ana",
      lastname: "Hurtado Garcia",
      awarded_specialty: "buzo",
      gender: "femenino",
      address: "calle libertad #203",
      foreign: true,
      country: "Bolivia",
      pre_university: "Saul",
      entrance_exams: ["Matematica"],
      academic_index: 4,
      grade_average: 5.6,
      scholarship_right: true,
      ces: "PUE",
    },
    type: ["Cambio", "Fijo"],
    description: "Cambio",
    allOfficials: false,
    awarded_career: "Informatica",
    education_center: "Uci",
    scholarship_right: false,
    // entrance_exams!: string[];
  },
];
